# Generated by Django 4.2.3 on 2023-10-21 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quillcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
