# Generated by Django 4.2.3 on 2023-10-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quillcart', '0002_alter_book_custom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='custom_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
