# Generated by Django 4.2.3 on 2023-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quillcart', '0003_book_id_alter_book_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='custom_id',
            field=models.DecimalField(decimal_places=0, max_digits=13, primary_key=True, serialize=False),
        ),
    ]
